-- =========================================================
-- SEED v2: MASTER DATA (sumber: DATABASE.xlsx, TA 2026)
-- Jalankan SETELAH 20260714100001_init_schema_v2.sql
-- Catatan:
--  * Tahapan DPA di-seed sebagai 'murni' -- sesuaikan lewat aplikasi.
--  * NIP PPTK di sini diisi placeholder 'TBD' (file sumber cuma punya
--    nama) -- WAJIB dilengkapi manual oleh Admin lewat halaman PPTK.
--  * Data KPA & Bendahara Pengeluaran Pembantu (pejabat_skpd) diisi dari
--    contoh dokumen yang pernah dilampirkan -- CEK ULANG sebelum dipakai.
-- =========================================================

-- ---- PEJABAT SKPD: KPA & BENDAHARA PENGELUARAN PEMBANTU ----
insert into pejabat_skpd (jabatan, nama, nip, tahun_anggaran) values ('KPA', 'Dra. EMILYATI, M.Si', '19690118 199003 2 002', 2026) on conflict (jabatan, tahun_anggaran) do nothing;
insert into pejabat_skpd (jabatan, nama, nip, tahun_anggaran) values ('BENDAHARA_PENGELUARAN_PEMBANTU', 'IRSYA YURISTIN', '19830728 200701 2 004', 2026) on conflict (jabatan, tahun_anggaran) do nothing;

-- ---- PROGRAM ----
insert into program (kode_program, nama_program, tahun_anggaran) values ('4.01.01', 'Program Penunjang Urusan Pemerintahan Kabupaten/Kota', 2026) on conflict (kode_program, tahun_anggaran) do nothing;
insert into program (kode_program, nama_program, tahun_anggaran) values ('4.01.03', 'Program Perekonomian dan Pembangunan', 2026) on conflict (kode_program, tahun_anggaran) do nothing;

-- ---- KEGIATAN ----
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.02', 'Administrasi Keuangan Perangkat Daerah', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.05', 'Administrasi Kepegawaian Perangkat Daerah', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.06', 'Administrasi Umum Perangkat Daerah', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.07', 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintahan Kabupaten/Kota', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.08', 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.01.2.09', 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Kabupaten/Kota', 2026 from program where kode_program = '4.01.01' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.03.2.01', 'Pelaksanaan Kebijakan Perekonomian', 2026 from program where kode_program = '4.01.03' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;
insert into kegiatan (program_id, kode_kegiatan, nama_kegiatan, tahun_anggaran) select id, '4.01.03.2.04', 'Pemantauan Kebijakan Sumber Daya Alam', 2026 from program where kode_program = '4.01.03' and tahun_anggaran = 2026 on conflict (kode_kegiatan, tahun_anggaran) do nothing;

-- ---- SUB KEGIATAN ----
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.02.0002', 'Penyediaan Administrasi Pelaksanaan Tugas ASN', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.02' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.05.0009', 'Pendidikan dan Pelatihan Pegawai Berdasarkan Tugas dan Fungsi', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.05' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.06.0002', 'Penyediaan Peralatan dan Perlengkapan Kantor', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.06' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.06.0003', 'Penyediaan Peralatan Rumah Tangga', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.06' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.06.0004', 'Penyediaan Bahan Logistik Kantor', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.06' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.06.0009', 'Penyelenggaraan Rapat Koordinasi dan Konsultasi SKPD', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.06' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.07.0006', 'Pengadaan Peralatan dan Mesin Lainnya', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.07' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.08.0004', 'Penyediaan Jasa Pelayanan Umum Kantor', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.08' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.09.0002', 'Penyediaan Jasa Pemeliharaan, Biaya Pemeliharaan, Pajak dan Perizinan Kendaraan Dinas Operasional atau Lapangan', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.09' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.01.2.09.0006', 'Pemeliharaan Peralatan dan Mesin Lainnya', 2026 from kegiatan where kode_kegiatan = '4.01.01.2.09' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.01.0001', 'Koordinasi, Sinkronisasi, Monitoring dan Evaluasi Kebijakan Pengelolaan BUMD dan BLUD', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.01' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.01.0002', 'Pengendalian dan Distribusi Perekonomian', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.01' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.01.0003', 'Perencanaan dan Pengawasan Ekonomi Mikro Kecil', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.01' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.01.0006', 'Koordinasi, Sinkronisasi dan Evaluasi Pelaksanaan Tugas Tim Percepatan Akses Keuangan Daerah (TPAKD)', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.01' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.04.0001', 'Koordinasi, Sinkronisasi dan Evaluasi Kebijakan Pertanian, Kehutanan, Kelautan dan Perikanan', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.04' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.04.0002', 'Koordinasi, Sinkronisasi dan Evaluasi Kebijakan Pertambangan dan Lingkungan Hidup', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.04' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;
insert into sub_kegiatan (kegiatan_id, kode_sub_kegiatan, nama_sub_kegiatan, tahun_anggaran) select id, '4.01.03.2.04.0003', 'Koordinasi, Sinkronisasi dan Evaluasi Kebijakan Energi dan Air', 2026 from kegiatan where kode_kegiatan = '4.01.03.2.04' and tahun_anggaran = 2026 on conflict (kode_sub_kegiatan, tahun_anggaran) do nothing;

-- ---- REKENING BELANJA ----
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.01.03.007.00001', 'Belanja Honorarium Penanggungjawaban Pengelola Keuangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.02.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.01.03.007.00002', 'Belanja Honorarium Pengadaan Barang/Jasa', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.02.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.01.03.008.00002', 'Belanja Jasa Pengelolaan BMD yang Tidak Menghasilkan Pendapatan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.02.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00038', 'Kontribusi Kursus Singkat/ Pelatihan/ Sosialisasi/ Bimtek/ Diklat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.05.0009' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00024', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Tulis Kantor', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00025', 'Belanja Alat/Bahan untuk Kegiatan Kantor- Kertas dan Cover', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00027', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Benda Pos', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00029', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Bahan Komputer', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00031', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Listrik', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00036', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat/Bahan untuk Kegiatan Kantor Lainnya', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00030', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Perabot Kantor', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00036', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat/Bahan untuk Kegiatan Kantor Lainnya', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00045', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0004' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0009' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.04.001.00001', 'Belanja Perjalanan Dinas Biasa', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0009' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.2.02.05.001.00004', 'Belanja Modal Alat Penyimpan Perlengkapan Kantor', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.07.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00024', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Tulis Kantor', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.08.0004' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00030', 'Belanja Jasa Tenaga Kebersihan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.08.0004' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00067', 'Belanja Pembayaran Pajak, Bea, dan Perizinan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.03.002.00036', 'Belanja Pemeliharaan Alat Angkutan-Alat Angkutan Darat Bermotor-Kendaraan Bermotor Penumpang', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.03.002.00038', 'Belanja Pemeliharaan Alat Angkutan-Alat Angkutan Darat Bermotor-Kendaraan Bermotor Beroda Dua', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.03.002.00405', 'Belanja Pemeliharaan Komputer-Komputer Unit-Personal Computer', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.03.002.00409', 'Belanja Pemeliharaan Komputer-Peralatan Komputer-Peralatan Personal Computer', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00004', 'Honorarium Tim Pelaksana Kegiatan dan Sekretariat Tim Pelaksana Kegiatan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.005.00043', 'Belanja Sewa Hotel', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.009.00014', 'Belanja Jasa Konsultansi Berorientasi Layanan-Jasa Khusus', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.012.00001', 'Belanja Kursus Singkat/Pelatihan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00004', 'Honorarium Tim Pelaksana Kegiatan dan Sekretariat Tim Pelaksana Kegiatan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00047', 'Belanja Jasa Penyelenggaraan Acara', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00047', 'Belanja Jasa Penyelenggaraan Acara', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00004', 'Honorarium Tim Pelaksana Kegiatan dan Sekretariat Tim Pelaksana Kegiatan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00047', 'Belanja Jasa Penyelenggaraan Acara', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00026', 'Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Tulis Kantor (DBH CHT)', 'DBH CHT' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat (DBH CHT)', 'DBH CHT' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan (DBH CHT)', 'DBH CHT' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia (DBH CHT)', 'DBH CHT' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.04.001.00001', 'Belanja Perjalanan Dinas Biasa (DBH CHT)', 'DBH CHT' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.04.001.00004', 'Belanja Perjalanan Dinas Dalam Kota', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00052', 'Belanja Makanan dan Minuman Rapat', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.01.001.00058', 'Belanja Makanan dan Minuman Aktivitas Lapangan', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;
insert into rekening_belanja (sub_kegiatan_id, kode_rekening, jenis_belanja, sumber_dana) select id, '5.1.02.02.001.00003', 'Honorarium Narasumber atau Pembahas, Moderator, Pembawa Acara, dan Panitia', 'PAD' from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, kode_rekening, sumber_dana) do nothing;

-- ---- PPTK per Sub Kegiatan (nama langsung dari file; NIP placeholder 'TBD') ----
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.02.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.05.0009' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0004' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.06.0009' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.07.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.08.0004' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.01.2.09.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Sari Anas Putri', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Diyah Wahyuni', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Diyah Wahyuni', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Diyah Wahyuni', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.01.0006' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0001' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0002' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;
insert into pptk (sub_kegiatan_id, nama, nip, tahun_anggaran) select id, 'Tengko Wolok', 'TBD', 2026 from sub_kegiatan where kode_sub_kegiatan = '4.01.03.2.04.0003' and tahun_anggaran = 2026 on conflict (sub_kegiatan_id, tahun_anggaran) do nothing;

-- ---- DPA (pagu awal, tahapan default 'murni' -- SESUAIKAN) ----
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 59220000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.01.03.007.00001' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 8160000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.01.03.007.00002' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3600000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.02.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.01.03.008.00002' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 15000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.05.0009' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.05.0009' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00038' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 4456499, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00024' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 6619040, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00025' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 1170000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00027' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 1434000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00029' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 313200, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00031' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3250000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00036' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 4183600, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00030' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00036' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 5480000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0004' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0004' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00045' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 1320000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0009' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0009' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 36068000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.06.0009' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.06.0009' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.04.001.00001' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 8348800, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.07.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.07.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.2.02.05.001.00004' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 329052, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.08.0004' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.08.0004' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00024' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 32100000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.08.0004' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.08.0004' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00030' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 7150000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00067' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 33600000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.03.002.00036' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 29200000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.09.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.03.002.00038' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 2190000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.09.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.09.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.03.002.00405' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 1380000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.01.2.09.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.01.2.09.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.03.002.00409' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 14412500, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 65100000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 14200000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00004' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 6000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.005.00043' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 55000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.009.00014' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 17000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.012.00001' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 34680000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3300000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 13100000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00004' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 50000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00047' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 10200000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 16000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 50000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00047' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00004' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.01.0006' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00047' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00026' and r.sumber_dana = 'DBH CHT' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 5812500, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 8860000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'DBH CHT' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3300000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 1237500, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'DBH CHT' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3600000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 11200000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'DBH CHT' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 18040000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.04.001.00001' and r.sumber_dana = 'DBH CHT' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 5000000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0001' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.04.001.00004' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 2625000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 2750000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0002' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 2700000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00052' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 3300000, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.01.001.00058' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;
insert into dpa (rekening_id, tahun_anggaran, tahapan, pagu_anggaran, pptk_id) select r.id, 2026, 'murni', 0, (select pp.id from pptk pp join sub_kegiatan sk2 on sk2.id = pp.sub_kegiatan_id  where sk2.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk2.tahun_anggaran = 2026 limit 1) from rekening_belanja r join sub_kegiatan sk on sk.id = r.sub_kegiatan_id where sk.kode_sub_kegiatan = '4.01.03.2.04.0003' and sk.tahun_anggaran = 2026 and r.kode_rekening = '5.1.02.02.001.00003' and r.sumber_dana = 'PAD' on conflict (rekening_id, tahun_anggaran, tahapan) do nothing;